version: "3.3"
services:
  socket_server:
    container_name: socket_server
    build: .
    volumes:
      - server_chat:/socket_server
      - node_modules:/socket_server/node_modules

    ports:
    - 8020:8020
    stdin_open: true
    command: npm start
volumes:
  node_modules: