version: "3.3"
services:
  server_chat:
    container_name: server_chat
    build: .
    volumes:
      - server_chat:/server_chat
      - node_modules:/server_chat/node_modules

    ports:
    stdin_open: true
    command: npm start
volumes:
  node_modules: